store/config/routes.rb
Rails.application.routes.draw do
  resources :departments
  get 'products/search', to: 'products#search', as: :search_product
  resources :products, only: [:new, :create, :destroy, :edit, :update]
  root to: 'products#index'
end

store/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

store/app/models/department.rb
class Department < ApplicationRecord
end

store/app/models/product.rb
class Product < ApplicationRecord
  belongs_to :department, optional: true

  validates :price, presence: true
  validates :name, length: { minimum: 4 }
end

store/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

store/app/controllers/departments_controller.rb
class DepartmentsController < ApplicationController
  before_action :set_department, only: [:show, :edit, :update, :destroy]

  # GET /departments
  # GET /departments.json
  def index
    @departments = Department.all
  end

  # GET /departments/1
  # GET /departments/1.json
  def show
    @products_per_department = Product.where('department_id = ?', params[:id])
  end

  # GET /departments/new
  def new
    @department = Department.new
  end

  # GET /departments/1/edit
  def edit
  end

  # POST /departments
  # POST /departments.json
  def create
    @department = Department.new(department_params)

    respond_to do |format|
      if @department.save
        format.html { redirect_to @department, notice: 'Department was successfully created.' }
        format.json { render :show, status: :created, location: @department }
      else
        format.html { render :new }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /departments/1
  # PATCH/PUT /departments/1.json
  def update
    respond_to do |format|
      if @department.update(department_params)
        format.html { redirect_to @department, notice: 'Department was successfully updated.' }
        format.json { render :show, status: :ok, location: @department }
      else
        format.html { render :edit }
        format.json { render json: @department.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /departments/1
  # DELETE /departments/1.json
  def destroy
    @department.destroy
    respond_to do |format|
      format.html { redirect_to departments_url, notice: 'Department was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_department
      @department = Department.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def department_params
      params.require(:department).permit(:name)
    end
end

store/app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:edit, :update, :destroy]

  def index
    @products = Product.order(name: :asc).limit 6
    @products_with_discount = Product.order(:price).limit 1
  end

  def new
    @product = Product.new
    @departments = Department.all
  end

  def edit
    renders :edit
  end

  def update
    if @product.update product_params
      flash[:notice] = 'Produto atualizado com sucesso!'
      redirect_to root_url
    else
      renders :edit
    end
  end

  def create
    @product = Product.new product_params
    if @product.save
      flash[:notice] = 'Produto salvo com sucesso!'
      redirect_to root_url
    else
      renders :new
    end
  end

  def destroy
    @product.destroy
    redirect_to root_url
  end

  def search
    @name = params[:name]
    @products = Product.where 'name like ?', "%#{@name}%"
  end

  private

  def product_params
    params.require(:product).permit(:name, :description, :price, :amount, :department_id)
  end

  def set_product
    @product = Product.find(params[:id])
  end

  def renders(view)
    @departments = Department.all
    render view
  end
end

store/app/helpers/application_helper.rb
module ApplicationHelper
end

store/app/helpers/departments_helper.rb
module DepartmentsHelper
end

store/app/helpers/products_helper.rb
module ProductsHelper
end

store/app/views/departments/_form.html.erb
<%= form_with(model: department, local: true) do |form| %>
  <% if department.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(department.errors.count, "error") %> prohibited this department from being saved:</h2>

      <ul>
        <% department.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

store/app/views/departments/edit.html.erb
<h1>Editing Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Departamentos', @department, class:"btn btn-default" %>
<%= link_to 'Voltar', departments_path, class:"btn btn-default" %>

store/app/views/departments/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Departments</h1>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @departments.each do |department| %>
      <tr>
        <td><%= department.name %></td>
        <td><%= link_to 'Ver produtos', department, class:"btn btn-default" %></td>
        <td><%= link_to 'Editar', edit_department_path(department), class:"btn btn-default" %></td>
        <td><%= link_to 'Deletar', department, method: :delete, data: { confirm: 'Tem certeza que deseja deletar?' }, class:"btn btn-default" %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Criar Novo Departamento', new_department_path, class:"btn btn-default" %>

store/app/views/departments/new.html.erb
<h1>New Department</h1>

<%= render 'form', department: @department %>

<%= link_to 'Back', departments_path %>

store/app/views/departments/show.html.erb
<p id="notice"><%= notice %></p>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
        <td>Nome</td>
        <td>Descrição</td>
        <td>Departamento</td>
        <td>Preço</td>
        <td>Quantidade</td>
        <td colspan="2"></td> 
    </tr>
  </thead>
  <tbody>
    <%= render @products_per_department %>
  </tbody>
</table>

<%= link_to 'Editar departamento', edit_department_path(@department), class:"btn btn-default" %>
<%= link_to 'Voltar', departments_path, class:"btn btn-default" %>

store/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Store</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= nav_bar brand: "Store", brand_link: root_url do %>
    <%= menu_group do %>
      <%= menu_item "Criar Novo Produto", new_product_path %>
      <%= menu_item "Departamentos", departments_path%>
    <% end %>
    <%= form_tag search_product_path, method: :get, class:"navbar-form navbar-right" do %>
        <div class="form-group">
          <%= text_field_tag :name, @name, class:"form-control" %>
          <%= button_to "Buscar", nil, class:"btn btn-default" %>
        </div>
      <% end %>
  <% end %>
    <div class="container">
        <%= yield %>
    </div>
  </body>
</html>

store/app/views/products/_form.html.erb
<% @product.errors.full_messages.each do |msg| %>
    <div class="alert alert-danger" role="alert">
        <%= msg %>    
    </div>
<% end %>

<%= form_for @product do |form| %> 
  <div class="row">
      <div class="col-sm-6">
          <div class="form-group">
            <%= form.label :nome %>
            <%= form.text_field :name, class:"form-control" %>
          </div>
      </div>
  </div>  

  <div class="row">
      <div class="col-sm-8">
          <div class="form-group">
            <%= form.label :descrição%>
            <%= form.text_area :description, class:"form-control", rows:4%>
          </div>
      </div>
  </div>

  <div class="row">
    <div class="col-sm-2">
          <div class="form-group">
              <%= form.label :departamento%>
              <%= form.collection_select :department_id, @departments, :id, :name, {}, class:"form-control" %>
          </div>
      </div>
  </div>

  <div class="row">
      <div class="col-sm-2">
          <div class="form-group">
              <%= form.label :preço%>
              <%= form.number_field :price, step:0.01, class:"form-control"%>
          </div>
      </div>
  </div>

  <div class="row">
    <div class="col-sm-2">
          <div class="form-group">
              <%= form.label :quantidade%>
              <%= form.number_field :amount, class:"form-control"%>
          </div>
      </div>
  </div>
  <%= form.submit action_text, class:"btn btn-primary"%>
<% end %>

store/app/views/products/_product.html.erb
<tr>
  <td><%= product.name %></td>
  <td><%= product.description %></td>
  <td><%= product.department.name %></td>
  <td><%= product.price %></td>
  <td><%= product.amount %></td>
  <td><%= link_to "Alterar", edit_product_path(product), class:"btn btn-default" %></td>
  <td><%= button_to "Remover", product, method: :delete, class:"btn btn-danger",
  data: {confirm: "Tem certeza que deseja remover o produto #{product.name}?"} %></td>
</tr>

store/app/views/products/edit.html.erb
<%= render partial: "form", locals: { action_text: "Atualizar" } %>

store/app/views/products/index.html.erb
<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= flash[:notice] %>
  </div>
<% end %>

<table class="table table-bordered table-hover">
  <thead>
    <tr>
        <td>Nome</td>
        <td>Descrição</td>
        <td>Departamento</td>
        <td>Preço</td>
        <td>Quantidade</td>
        <td colspan="2"></td> 
    </tr>
  </thead>
  <tbody>
    <%= render @products %>
  </tbody>
</table>
<div class="alert alert-success" role="alert">
    <h4 class="alert-heading">Produto com Desconto</h4>
</div>
<table class="table table-bordered table-hover">
  <thead>
    <tr>
        <td>Nome</td>
        <td>Descrição</td>
        <td>Departamento</td>
        <td>Preço</td>
        <td>Quantidade</td>
        <td colspan="2"></td> 
    </tr>
  </thead>
  <tbody>
  <%= render @products_with_discount %>
  </tbody>
</table>

store/app/views/products/new.html.erb
<%= render partial: "form", locals: { action_text: "Criar" } %>

store/app/views/products/search.html.erb
<table class="table table-bordered table-hover">
  <thead>
    <tr>
        <td>Nome</td>
        <td>Descrição</td>
        <td>Preço</td>
        <td>Quantidade</td>
        <td colspan="1"></td> 
    </tr>
  </thead>
  <tbody>
  <% @products.each do |product| %>
    <tr>
      <td><%= product.name %></td>
      <td><%= product.description %></td>
      <td><%= product.price %></td>
      <td><%= product.amount %></td>
      <td><%= button_to "Remover", product, method: :delete, class:"btn btn-danger",
      data: {confirm: "Tem certeza que deseja remover o produto #{product.name}?"} %></td>
    </tr>
    <% end %>
  </tbody>
</table>